Vendor btree
travisturner/pilosa pull request #9
Opened 2018-01-19 22:11 UTC by tgruben

prevent allocs from occurring on PutConainerValues if container exists

2018-02-02 21:25 UTC, travisturner commented on roaring/assembly_test.go
> +var Result uint64
does `Result` get returned somewhere?

2018-02-02 21:25 UTC, travisturner commented on roaring/containers_slice.go
> +		//should this happen?
it seems like it should. why the question?

2018-02-02 21:25 UTC, travisturner commented on roaring/containers_btree.go
> +type updater struct {
just curious, does it help to have this `updater` struct? or is it just for code organizational purposes?
(i.e. is there anything functionally different besides returning `false` in the "exists" path?)

2018-02-05 14:05 UTC, tgruben commented on roaring/assembly_test.go
> +var Result uint64
this prevents the optimizer from removing the code that the benchmark is supposed to test

2018-02-05 14:07 UTC, tgruben commented on roaring/containers_btree.go
> +type updater struct {
yeah, this struct is used to hint to the compiler that the closure should just allocate on the stack,   without it escapes out to the heap

2018-02-05 14:31 UTC, tgruben commented on roaring/containers_slice.go
> +		//should this happen?
yeah, that should be removed.  It was just a note to myself as i was thinking

2018-02-05 17:42 UTC, travisturner requested changes

2018-02-05 17:42 UTC, travisturner commented on fragment.go
> +		f.storage = roaring.NewBitmapBtree()
For consistency with the other methods, can we rename this to `NewBTreeBitmap` (note also the capitalized `T` in tree)

2018-02-05 17:42 UTC, travisturner commented on roaring/assembly_test.go
> +var Result uint64
I suggest adding a comment in the code with this information.

2018-02-05 17:42 UTC, travisturner commented on roaring/containers_btree.go
> +type updater struct {
add a comment with this information

2018-02-05 17:42 UTC, travisturner commented on roaring/containers_test.go
> +	//btc := NewBTreeContainers()
can we modify the tests so that both container implementations get tested?

2018-02-05 20:34 UTC, travisturner approved these changes

2018-02-05 20:35 UTC, merged